services:
  nodo-a:
    build: .
    command: sh -c "rm -rf __pycache__ && /usr/local/bin/python -u The_Initiator.py"
    ports:
      - "8080:8080"
    networks:
      - app-network

  nodo-b:
    build: .
    command: sh -c "rm -rf __pycache__ && /usr/local/bin/python -u The_Transformer.py"
    networks:
      - app-network

  nodo-c:
    build: .
    command: sh -c "rm -rf __pycache__ && /usr/local/bin/python -u The_Auditor.py"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
